### PR TITLE
C 001

### PR DESCRIPTION
**Pull request by murilocamargos**
### How the solution works

The solution just checks whether the number if multiple of 3 or 5.

### Performance

[C](https://tio.run/##JY3BCoMwEETPyVcMFiFiWyKlJ7X/IkbbBbtKGk/Vb083FvbwHjPL9Jd@6vgZ44m4n1Y3oPkER/P19dCaOODdEZsCX62S0RmMFrbWUOPsYUisqkFoUFlrhcryaCsaU5rjhlYesG1Idj/s31CMsgXVgrtOt3jZGE2Wu0x2Cgn8EFbPxgpjj/EH)

```
Real time: 0.086 s
User time: 0.055 s
Sys. time: 0.027 s
CPU share: 94.53 %
Exit code: 0
```

### CODE REVIEW

**Comment by lucaspbordignon** [comment]
@murilocamargos Awesome contribution! Just follow the @FrankKair comments.

C's performance is blazingly fast! 🔥

**Comment by FrankKair** [comment]
Also, don't forget to rebase to sync with master (`git rebase master` and `git push -f`). 👍🏻

**Comment by caian-gums** [comment]
@murilocamargos, if you want to get it faster, see my solution in C++! I think you can optimize even more your solution!
👍

**Comment by fredericojordan** [comment]
Performance fight! 👊

**Pull request merged**
