### PR TITLE
Clojure 005

### PR DESCRIPTION
**Pull request by yvendruscolo**
### How the solution works

candidates: a range from 2520 *  2 (the since we are adding 16, another power of 2) * the four primes between 10 and 20 (11 13 17 19) up to 2 * the product of odd numbers from 3 to 19

div?:  gets integer a, return predicate that checks if new integer b is divisible by a

I generate a predicate that is the "composition" of applying 'div? to the range 20 to 6 by -1,
and get the first logical true out of the 'candidates' collection.

### Performance

[Try it online!](https://tio.run/##jZHBasMwEETv/oqBUFgFDJVDCDnlQ4QPwtoUFUUysuOQ/ry7dhpqQhuim1aaN7O7TUif58zjSI6PEV0KA8PUBUCBe5jGRued7bkDZRs/GLSG1tAb6B30HtW2ekelRPDfoczu3DDWqO6MDWbRM9UC6fxwAEk6E2us6ItzOkzUE94Q1YLSihPItm24ggfO1/JW8bFP0hToZNuZpu5BJMYWpV5CRFGK1@RHJnNXS6X7MymZFBwiX4Tsj6DZTK4KT/p6mMpN8ML/6IOkrIvHqf7ElWf87mrqp5A80sK8UaXG8Rs "Clojure – Try It Online")

```
Real time: 2.474 s
User time: 4.471 s
Sys. time: 0.169 s
CPU share: 187.50 %
```

### CODE REVIEW

**Comment by yvendruscolo** [comment]
halt-when was added in 1.9, while tio.run uses Clojure 1.7 ):

**Comment by FrankKair** [comment]
Ok, then add to the pull request's description that for now, TIO could't run the code due to its older Clojure version. That way we know why there isn't a TIO link 😊👍🏼

**Comment by yvendruscolo** [comment]
may I close the pr and look for a TIO compliant solution?

**Comment by FrankKair** [comment]
Whatever suits you best 😊 No worries

**Pull request merged**
