### PR TITLE
Adding problem 024

### PR DESCRIPTION
**Pull request by fredericojordan**
### How the solution works

There are `n!` possible permutations of `n` objects.
If you choose the first one, there are `(n-1)!` possible permutations of the remaining objects.
If we divide (and floor) the intended index by `(n-1)!`, we get the corresponding index of the first digit and the remainder of this division gives us the new index for the sublist (now with an element removed).
This way we can compute individual indexes without the need of recursion, making this solution extremely fast!

### Performance

[Try it online!](https://tio.run/##fZJNa8MwDIbv@RUau8TDTZOu@4T1tkPZYLuXENxYbQ2OExwnC6z77Zmdj7ajZYeA80p65FcyStEI3bbXV9Oq1NO1UFNUNWAnexw3Wc4rifCp87XELJzNgecegI0UsGGpybVg0o8ItfozROehhsDXDhWIMhHK4Ba1k5ji0MACor6uuTkpmETEGzkF6qwyzKC/2iHjMYWEAkvToV8nwt4pMewX8KqqLNBYoy7RJ05Z9j2DSnGxFab0yTlaitJQEIpj08N7jwDfICgYJiT8wEunALjk4Wjx7/YvKPIiYcbnovYHiD0Kbp26ZEJIl3/s54gUNGaX0ymsQPSmIHa1qPi/lx6GcTE2sRNexceB/mk1@jx4GkeY5pUyPhm1N9QKZTCxex6lw76G@/V8KHNZ44g9WV5IIzqjt3RO7@g9faCP9MnuMkrCMHTf6LIjLT@CojLlyZsLOqzXtr8)

```
Real time: 0.768 s
User time: 0.374 s
Sys. time: 0.289 s
CPU share: 86.35 %
Exit code: 0
```

### CODE REVIEW

**Comment by fredericojordan** [comment]
[Try it online](https://tio.run/) has the advantage of encoding the whole program on the URI (I think), which facilitates it's maintenance, IMO.

**Comment by fredericojordan** [comment]
I have just reordered the functions! Thanks!
On a second note, am I missing something or is this rebase really necessary? Isn't my branch just adding 2 new files?

**Comment by FrankKair** [comment]
@fredericojordan I think it's nice having the master branch well structured, but sure it's no problem. Mostly aesthetic, since we aren't going back and forth on the tree to solve problems or find bugs.

**Comment by fredericojordan** [comment]
Oh, I see your point. I'll rebase next time, thanks!

**Pull request merged**
