### PR TITLE
Feat: Adds CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by FrankKair**
This pull request tries to come up with a framework and guideline for contributions, as discussed in #14.

What do you guys think?

### CODE REVIEW

**Comment by FrankKair** [comment]
@caian-gums Regarding naming conventions, yes, each language have their own "case". Swift, Java, Scala all use `camelCase`, whereas Python, Ruby, Lua, Elixir all use `snake_case`. We even have the odd man out Clojure with `kebab-case` 😅.

**Comment by FrankKair** [comment]
@caiopo pointed out that only calling a solve function gives no context whatsoever to the reader, and he's right.

This is an issue for simple problems, I guess, because when we have a somewhat more complicated challenge, we always abstract away some pieces of computation. Maybe we should keep the same idea for smaller problems as well, like [this](https://github.com/FrankKair/polyglot-euler/blob/master/src/002/p002.lua). Even if the computation is done in one loop, we could still provide meaningful information, and afterwards call the general function in an enclosing `solve` function.

Any thoughts?

**Comment by FrankKair** [comment]
@fredericojordan I know very little about these languages, maybe you could take care of Clojure? 😆
@caiopo Could describe the best approach for Haskell and @lucaspbordignon gets Scala.

**Comment by lucaspbordignon** [comment]
@FrankKair for sure, I will take a look on the docs and patterns for Scala tonight! 😄

**Comment by caiopo** [comment]
I'd suggest the following style for Haskell files:

---
### Haskell

```haskell
function1 :: a -> b
function1 x = -- Body

function2 :: b -> c
function2 y = -- Body

main :: IO
main = print $ -- Call other functions
```
Note: type signatures are mandatory to all top-level functions.

---

Markdown:

    ### Haskell

    ```haskell
    function1 :: a -> b
    function1 x = -- Body

    function2 :: b -> c
    function2 y = -- Body

    main :: IO
    main = print $ -- Call other functions
    ```
    Note: type signatures are mandatory to all top-level functions.

**Comment by caiopo** [comment]
Someone accidentally deleted @lucaspbordignon's commit. Let's be careful when force-pushing, please.

**Comment by fredericojordan** [comment]
Clojure is pretty straight-forward:

---
### Clojure

```clojure
(defn function1 [x]
  ; function body
)

(defn solve [] (function1 a))

(prn (solve))
```

---

Markdown:

    ### Clojure
    
    ```clojure
    (defn function1 [x]
      ; function body
    )
    
    (defn solve [] (function1 a))
    
    (prn (solve))
    ```

**Pull request merged**
